name: thesis server build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_libbpf_bootstrap:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        llvm: [11, 12, 13, 14, 15, 16, 17]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build container (20.04)
      if: ${{ matrix.llvm < 14 }}
      uses: docker/build-push-action@v3
      with:
        push: false
        build-args: |
          LLVM_VERSION=${{ matrix.llvm }}
          VERSION=20.04
          SHORTNAME=focal
        file: ./.github/docker/Dockerfile.ubuntu
        tags: build_container
    - name: Build container (22.04)
      if: ${{ matrix.llvm >= 14 }}
      uses: docker/build-push-action@v3
      with:
        push: false
        build-args: |
          LLVM_VERSION=${{ matrix.llvm }}
          VERSION=22.04
          SHORTNAME=jammy
        file: ./.github/docker/Dockerfile.ubuntu
        tags: build_container
    - name: Build server
      run: |
        docker run \
          -v $(pwd):/thesis \
          build_container \
          /bin/bash -c \
          'mkdir /thesis/build && cd /thesis/build && CXX=/usr/bin/clang cmake ../src/ && make'
