name: thesis server build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_libbpf_bootstrap:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        llvm: [14, 15, 16]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build container
      uses: docker/build-push-action@v3
      with:
        push: false
        build-args: LLVM_VERSION=${{ matrix.llvm }}
        file: ./.github/docker/Dockerfile.ubuntu
        tags: build_container
    - name: Build server
      run: |
        docker run \
          -v $(pwd):/thesis \
          build_container \
          /bin/bash -c \
          'mkdir /thesis/build && cd /thesis/build && CXX=/usr/bin/clang cmake ../src/ && make'
